/**
 * diff-logger.ts — OpenCode local plugin
 *
 * Maintains .opencode/changes.md as a human-readable changelog of every file
 * change made by OpenCode sessions.
 *
 * HOW IT WORKS
 *  - Primary trigger: `tool.execute.after` for write/edit tools → runs
 *    `git diff HEAD` and captures changes.
 *  - Secondary trigger: `session.diff` event → uses built-in snapshot diff
 *    data (includes +/- counts).
 *  - Writes ONE rolling entry per session — deduped by sessionID, newest at top.
 */
import type { Plugin } from "@opencode-ai/plugin";

const REL = ".opencode/changes.md";

const HEADER = [
  "# OpenCode Change Log",
  "Auto-generated by `.opencode/plugins/diff-logger.ts`.",
  "",
  "---",
  "",
].join("\n");

/** Read existing entries from changes.md, returning (header, entries-array). */
function readExisting(fullPath: string): string[] {
  let body = "";
  try {
    body = Bun.file(fullPath).text();
  } catch { /* first write */ }
  const sep = "\n---\n";
  const idx = body.indexOf(sep);
  const existing = idx >= 0 ? body.slice(idx + sep.length).trimStart() : "";
  return existing
    .split(/\n(?=## )/)
    .map((e) => e.trim())
    .filter((e) => e.length > 0);
}

/** Write entry to disk, deduped by sessionID. */
function writeEntry(fullPath: string, entry: string, sessionID: string): void {
  const kept = readExisting(fullPath).filter((e) => !e.includes(`<!-- ${sessionID} -->`));
  const out = HEADER + "\n" + entry + (kept.length ? "\n" + kept.join("\n\n") + "\n" : "\n");
  Bun.write(fullPath, out);
}

/** Run git status/diff and return [{file, add, del}]. */
function gitChanges(directory: string): Array<{ file: string; a: number; d: number }> {
  const results: Array<{ file: string; a: number; d: number }> = [];
  try {
    // Tracked file changes with +/- counts
    const proc = Bun.spawnSync(["git", "diff", "--stat", "HEAD"], { cwd: directory });
    const out = proc.stdout.toString().trim();
    if (out) {
      for (const line of out.split("\n")) {
        const m = line.match(/^(.+?)\s+\|\s+(\d+)\s+([+-]+)$/);
        if (m) {
          results.push({
            file: m[1].trim(),
            a: (m[3].match(/\+/g) || []).length,
            d: (m[3].match(/-/g) || []).length,
          });
        }
      }
    }
    // Untracked files (not in diff --stat)
    const untracked = Bun.spawnSync(
      ["git", "ls-files", "--others", "--exclude-standard"],
      { cwd: directory },
    );
    for (const file of untracked.stdout.toString().trim().split("\n").filter(Boolean)) {
      // Count lines in new files
      try {
        const fc = Bun.spawnSync(["wc", "-l", file], { cwd: directory });
        const a = parseInt(fc.stdout.toString().trim().split(/\s+/)[0], 10) || 0;
        results.push({ file, a, d: 0 });
      } catch {
        results.push({ file, a: 0, d: 0 });
      }
    }
  } catch { /* git not available */ }
  return results;
}

/** Build a markdown entry from change stats. */
function buildEntry(
  sessionID: string,
  title: string,
  stats: Array<{ file: string; a: number; d: number }>,
): string {
  const sorted = [...stats].sort((a, b) => a.file.localeCompare(b.file));
  const totals = sorted.reduce((acc, s) => ({ a: acc.a + s.a, d: acc.d + s.d }), { a: 0, d: 0 });
  const ts = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";
  const lines = sorted.map(
    (s) => `- [${s.a > 0 && s.d === 0 ? "A" : "M"}] \`${s.file}\` (+${s.a}/-${s.d})`,
  );
  return [
    `## ${ts} — ${title}  <!-- ${sessionID} -->`,
    "",
    `${sorted.length} file(s) changed — +${totals.a}/-${totals.d}`,
    "",
    ...lines,
    "",
  ].join("\n");
}

export const DiffLogger: Plugin = async ({ directory, client }) => {
  const fullPath = `${directory}/${REL}`;

  return {
    // ── Primary: detect write/edit tool completions ──
    "tool.execute.after": async (input, _output) => {
      if (input.tool !== "write" && input.tool !== "edit") return;

      const stats = gitChanges(directory);
      if (stats.length === 0) return;

      let title = input.sessionID?.slice(-12) ?? "session";
      try {
        const res = await client.session.get({ path: { sessionID: input.sessionID } });
        const t = ((res as any)?.data ?? res)?.title;
        if (t && String(t).trim()) title = String(t).trim();
      } catch { /* fallback */ }

      const entry = buildEntry(input.sessionID, title, stats);
      writeEntry(fullPath, entry, input.sessionID);
    },

    // ── Secondary: snapshot-based session.diff events ──
    event: async ({ event }) => {
      if (event.type !== "session.diff") return;

      const { sessionID, diff } = event.properties as { sessionID: string; diff: any[] };
      if (!Array.isArray(diff) || diff.length === 0) return;

      let title = sessionID?.slice(-12) ?? "session";
      try {
        const res = await client.session.get({ path: { sessionID } });
        const t = ((res as any)?.data ?? res)?.title;
        if (t && String(t).trim()) title = String(t).trim();
      } catch { /* fallback */ }

      const stats = diff
        .filter((d: any) => d.file)
        .map((d: any) => ({ file: d.file, a: d.additions ?? 0, d: d.deletions ?? 0 }));

      const entry = buildEntry(sessionID, title, stats);
      writeEntry(fullPath, entry, sessionID);
    },
  };
};

export default DiffLogger;
